# theme: jekyll-theme-tactile
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

collections:
  projects:
    output: true
    permalink: /projects/:name
  posts:
    output: true
    permalink: /blog/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"